from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(844, 484)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.ocrOut_2 = QtWidgets.QLabel(self.centralwidget)
        self.ocrOut_2.setFrameShape(QtWidgets.QFrame.Box)
        self.ocrOut_2.setText("")
        self.ocrOut_2.setScaledContents(True)
        self.ocrOut_2.setObjectName("ocrOut_2")
        self.gridLayout.addWidget(self.ocrOut_2, 0, 0, 0, 0)
        self.vidOut = QtWidgets.QLabel(self.centralwidget)
        self.vidOut.setFrameShape(QtWidgets.QFrame.Box)
        self.vidOut.setTextFormat(QtCore.Qt.AutoText)
        self.vidOut.setScaledContents(True)
        self.vidOut.setAlignment(QtCore.Qt.AlignCenter)
        self.vidOut.setObjectName("vidOut")
        self.gridLayout.addWidget(self.vidOut, 0, 0, 0, 0)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnCamera = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCamera.sizePolicy().hasHeightForWidth())
        self.btnCamera.setSizePolicy(sizePolicy)
        self.btnCamera.setMinimumSize(QtCore.QSize(200, 50))
        self.btnCamera.setMaximumSize(QtCore.QSize(200, 50))
        self.btnCamera.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnCamera.setObjectName("btnCamera")
        self.verticalLayout.addWidget(self.btnCamera)
        self.btnStopCamera = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStopCamera.sizePolicy().hasHeightForWidth())
        self.btnStopCamera.setSizePolicy(sizePolicy)
        self.btnStopCamera.setMinimumSize(QtCore.QSize(200, 50))
        self.btnStopCamera.setMaximumSize(QtCore.QSize(200, 50))
        self.btnStopCamera.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnStopCamera.setObjectName("btnStopCamera")
        self.verticalLayout.addWidget(self.btnStopCamera)
        self.btnFile = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFile.sizePolicy().hasHeightForWidth())
        self.btnFile.setSizePolicy(sizePolicy)
        self.btnFile.setMinimumSize(QtCore.QSize(200, 50))
        self.btnFile.setMaximumSize(QtCore.QSize(200, 50))
        self.btnFile.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnFile.setObjectName("btnFile")
        self.verticalLayout.addWidget(self.btnFile)
        self.btnDirectory = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDirectory.sizePolicy().hasHeightForWidth())
        self.btnDirectory.setSizePolicy(sizePolicy)
        self.btnDirectory.setMinimumSize(QtCore.QSize(200, 50))
        self.btnDirectory.setMaximumSize(QtCore.QSize(200, 50))
        self.btnDirectory.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnDirectory.setObjectName("btnDirectory")
        self.verticalLayout.addWidget(self.btnDirectory)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        self.btnExit.setMinimumSize(QtCore.QSize(200, 50))
        self.btnExit.setMaximumSize(QtCore.QSize(200, 50))
        self.btnExit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnExit.setObjectName("btnExit")
        self.verticalLayout.addWidget(self.btnExit)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Group 1 OCR Prototype"))
        self.vidOut.setText(_translate("MainWindow", "Video Turned Off"))
        self.btnCamera.setText(_translate("MainWindow", "Start Camera"))
        self.btnStopCamera.setText(_translate("MainWindow", "StopCamera"))
        self.btnFile.setText(_translate("MainWindow", "Open From File"))
        self.btnDirectory.setText(_translate("MainWindow", "Save Directory"))
        self.btnExit.setText(_translate("MainWindow", "Exit"))
